use_frameworks!
target 'ReNodeSample' do
  pod 'ReNode', :path => '../'
  
  pod "Texture"
  pod 'ReSwift'
  pod 'ReSwiftThunk'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'StorybookKit'
  pod 'DateTools'
  pod 'SnapKit'
  pod 'SVGgh'
  
end
